### ISSUE TITLE
Current released version of rom-csv depends on rom ~> 0.9.0

### ISSUE THREAD

**Issue by viking** [rom-rb/rom-csv#13]
This makes rom-csv impossible to use alongside rom-sql when installing via rubygems.

**Comment by solnic** [comment]
This gem has no official maintainer yet.

**Comment by gotar** [comment]
We use it in our project, @wafcio can you update deps?

**Comment by wafcio** [comment]
sure, I will do it today later

**Comment by cflipse** [comment]
It's already got the right set of dependencies; just needs to be released.

**Comment by wafcio** [comment]
released on rubygems https://rubygems.org/gems/rom-csv/versions/0.3.0
